codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "95...100"

  status:
    project:
      default:
        target: 95%
        threshold: 0%
    patch:
      default:
        target: 95%
        threshold: 0%

bundle_analysis:
  warning_threshold: "5%"
  status: "informational"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
