import type { ThemeSpec } from './types';

/**
 * The single source of truth for every theme. The registry keys *are* the theme
 * ids, so `ThemeId`, `THEMES`, and the exported list can never drift apart.
 * Individual palettes omit their id; it is attached when the registry is built.
 */
const THEME_SPECS = {
  dark: {
    name: 'Obsidian',
    mode: 'dark',
    description: 'Classic dark stone theme with vibrant neon cube accents',
    colors: {
      bgApp: '#0c0a09',
      bgCard: '#1c1917',
      bgSubtle: '#292524',
      bgHover: '#332e2b',
      border: '#292524',
      borderSubtle: '#44403c',
      textPrimary: '#f5f5f4',
      textSecondary: '#a8a29e',
      textMuted: '#78716c',
      accent: '#f59e0b',
      accentHover: '#fbbf24',
      accentMuted: 'rgba(245, 158, 11, 0.15)',
      accentText: '#fcd34d',
      series: {
        neutral: '#94a3b8',
        green: '#22c55e',
        orange: '#f97316',
        blue: '#0284c7',
        purple: '#a855f7',
        amber: '#eab308',
        red: '#e11d48',
        teal: '#14b8a6',
      },
      boxGradient: {
        start: '#dbeafe',
        end: '#1e3a8a',
      },
    },
  },
  light: {
    name: 'Clean Slate',
    mode: 'light',
    description:
      'Crisp white canvas with rich, high-contrast saturated lines and clear data profiles',
    colors: {
      bgApp: '#f8fafc',
      bgCard: '#ffffff',
      bgSubtle: '#f1f5f9',
      bgHover: '#e2e8f0',
      border: '#e2e8f0',
      borderSubtle: '#cbd5e1',
      textPrimary: '#0f172a',
      textSecondary: '#334155',
      textMuted: '#64748b',
      accent: '#0284c7',
      accentHover: '#0369a1',
      accentMuted: 'rgba(2, 132, 199, 0.12)',
      accentText: '#0369a1',
      series: {
        neutral: '#64748b',
        green: '#059669',
        orange: '#ea580c',
        blue: '#2563eb',
        purple: '#7c3aed',
        amber: '#b45309',
        red: '#dc2626',
        teal: '#0891b2',
      },
      boxGradient: {
        start: '#93c5fd',
        end: '#1e40af',
      },
    },
  },
  wca: {
    name: 'WCA Competition',
    mode: 'dark',
    description: 'Official WCA-inspired deep navy with royal blue and clean white lines',
    colors: {
      bgApp: '#090d1a',
      bgCard: '#11182c',
      bgSubtle: '#1a243f',
      bgHover: '#233054',
      border: '#1e2c4f',
      borderSubtle: '#2d3f6d',
      textPrimary: '#f8fafc',
      textSecondary: '#94a3b8',
      textMuted: '#64748b',
      accent: '#3b82f6',
      accentHover: '#60a5fa',
      accentMuted: 'rgba(59, 130, 246, 0.15)',
      accentText: '#93c5fd',
      series: {
        neutral: '#64748b',
        green: '#22c55e',
        orange: '#f59e0b',
        blue: '#3b82f6',
        purple: '#a855f7',
        amber: '#eab308',
        red: '#ef4444',
        teal: '#06b6d4',
      },
      boxGradient: {
        start: '#93c5fd',
        end: '#1e40af',
      },
    },
  },
  cyberpunk: {
    name: 'Cyberpunk Neon',
    mode: 'dark',
    description: 'High-contrast neon magenta, cyan, and electric yellow on deep obsidian',
    colors: {
      bgApp: '#080511',
      bgCard: '#130c26',
      bgSubtle: '#1d123a',
      bgHover: '#2a1a52',
      border: '#2c1955',
      borderSubtle: '#43267d',
      textPrimary: '#fdf4ff',
      textSecondary: '#d8b4fe',
      textMuted: '#9333ea',
      accent: '#f72585',
      accentHover: '#ff4d9d',
      accentMuted: 'rgba(247, 37, 133, 0.18)',
      accentText: '#fbcfe8',
      series: {
        neutral: '#7c3aed',
        green: '#00f5d4',
        orange: '#fee440',
        blue: '#00bbf9',
        purple: '#f72585',
        amber: '#ff9e00',
        red: '#ff0055',
        teal: '#22d3ee',
      },
      boxGradient: {
        start: '#00f5d4',
        end: '#7209b7',
      },
    },
  },
  'gan-mint': {
    name: 'GAN Mint',
    mode: 'dark',
    description: 'Sleek Arctic mint, teal, and ice blue inspired by modern GAN speedcubes',
    colors: {
      bgApp: '#071213',
      bgCard: '#0d1e21',
      bgSubtle: '#142a2f',
      bgHover: '#1c393f',
      border: '#18343b',
      borderSubtle: '#254b54',
      textPrimary: '#f0fdfa',
      textSecondary: '#99f6e4',
      textMuted: '#5eead4',
      accent: '#10b981',
      accentHover: '#34d399',
      accentMuted: 'rgba(16, 185, 129, 0.15)',
      accentText: '#a7f3d0',
      series: {
        neutral: '#94a3b8',
        green: '#10b981',
        orange: '#06b6d4',
        blue: '#38bdf8',
        purple: '#818cf8',
        amber: '#facc15',
        red: '#f43f5e',
        teal: '#2dd4bf',
      },
      boxGradient: {
        start: '#99f6e4',
        end: '#0d9488',
      },
    },
  },
  retro: {
    name: 'Retro 1980s',
    mode: 'dark',
    description: 'Warm charcoal with authentic 1980s primary Rubik sticker colors',
    colors: {
      bgApp: '#121214',
      bgCard: '#1a1a1e',
      bgSubtle: '#26262c',
      bgHover: '#32323a',
      border: '#2d2d35',
      borderSubtle: '#43434f',
      textPrimary: '#fafafa',
      textSecondary: '#d4d4d8',
      textMuted: '#a1a1aa',
      accent: '#eab308',
      accentHover: '#facc15',
      accentMuted: 'rgba(234, 179, 8, 0.15)',
      accentText: '#fef08a',
      series: {
        neutral: '#a1a1aa',
        green: '#22c55e',
        orange: '#f97316',
        blue: '#3b82f6',
        purple: '#eab308',
        amber: '#ec4899',
        red: '#ef4444',
        teal: '#06b6d4',
      },
      boxGradient: {
        start: '#fef08a',
        end: '#b45309',
      },
    },
  },
  monokai: {
    name: 'Monokai Pro',
    mode: 'dark',
    description: 'Code editor classic with vivid yellow, green, magenta, and orange',
    colors: {
      bgApp: '#1b1b1d',
      bgCard: '#222225',
      bgSubtle: '#2d2d31',
      bgHover: '#38383e',
      border: '#34343a',
      borderSubtle: '#46464f',
      textPrimary: '#fcfcfa',
      textSecondary: '#c1c0c0',
      textMuted: '#939293',
      accent: '#ffd866',
      accentHover: '#ffe699',
      accentMuted: 'rgba(255, 216, 102, 0.15)',
      accentText: '#fff3cc',
      series: {
        neutral: '#939293',
        green: '#a9dc76',
        orange: '#fc9867',
        blue: '#78dce8',
        purple: '#ab9df2',
        amber: '#ffd866',
        red: '#ff6188',
        teal: '#66d9ef',
      },
      boxGradient: {
        start: '#ffd866',
        end: '#fc9867',
      },
    },
  },
  'solarized-dark': {
    name: 'Solarized Dark',
    mode: 'dark',
    description: 'Precision low-contrast cyan and deep teal palette by Ethan Schoonover',
    colors: {
      bgApp: '#002b36',
      bgCard: '#073642',
      bgSubtle: '#0c4654',
      bgHover: '#135666',
      border: '#0e4a59',
      borderSubtle: '#185d6e',
      textPrimary: '#93a1a1',
      textSecondary: '#839496',
      textMuted: '#586e75',
      accent: '#2aa198',
      accentHover: '#35b7ad',
      accentMuted: 'rgba(42, 161, 152, 0.15)',
      accentText: '#7cd7d0',
      series: {
        neutral: '#586e75',
        green: '#859900',
        orange: '#cb4b16',
        blue: '#268bd2',
        purple: '#6c71c4',
        amber: '#b58900',
        red: '#dc322f',
        teal: '#2aa198',
      },
      boxGradient: {
        start: '#93a1a1',
        end: '#268bd2',
      },
    },
  },
  'solarized-light': {
    name: 'Solarized Light',
    mode: 'light',
    description: 'Warm ivory paper canvas with deep Ethan Schoonover solarized typography',
    colors: {
      bgApp: '#fdf6e3',
      bgCard: '#f5efdc',
      bgSubtle: '#eee8d5',
      bgHover: '#e7dec6',
      border: '#dcd3b5',
      borderSubtle: '#c6b991',
      textPrimary: '#073642',
      textSecondary: '#586e75',
      textMuted: '#586e75',
      accent: '#268bd2',
      accentHover: '#1b689e',
      accentMuted: 'rgba(38, 139, 210, 0.12)',
      accentText: '#144e76',
      series: {
        neutral: '#839496',
        green: '#5c6b00',
        orange: '#b23d0c',
        blue: '#1b689e',
        purple: '#555aa0',
        amber: '#936e00',
        red: '#b91c1c',
        teal: '#2aa198',
      },
      boxGradient: {
        start: '#859900',
        end: '#268bd2',
      },
    },
  },
  sunset: {
    name: 'Plum Sunset',
    mode: 'dark',
    description: 'Rich dark plum and coral rose paired with warm golden sunset hues',
    colors: {
      bgApp: '#130919',
      bgCard: '#1d0f28',
      bgSubtle: '#2a163a',
      bgHover: '#381f4d',
      border: '#361b4a',
      borderSubtle: '#4c2668',
      textPrimary: '#fff1f2',
      textSecondary: '#fecdd3',
      textMuted: '#fb7185',
      accent: '#f43f5e',
      accentHover: '#fb7185',
      accentMuted: 'rgba(244, 63, 94, 0.15)',
      accentText: '#ffe4e6',
      series: {
        neutral: '#a855f7',
        green: '#f43f5e',
        orange: '#fb923c',
        blue: '#c084fc',
        purple: '#e879f9',
        amber: '#facc15',
        red: '#e11d48',
        teal: '#2dd4bf',
      },
      boxGradient: {
        start: '#fb923c',
        end: '#c084fc',
      },
    },
  },
  'nord-light': {
    name: 'Nord Frost',
    mode: 'light',
    description: 'Cool arctic aesthetic with crisp snow canvas and vibrant glacial tones',
    colors: {
      bgApp: '#eceff4',
      bgCard: '#ffffff',
      bgSubtle: '#e5e9f0',
      bgHover: '#d8dee9',
      border: '#d8dee9',
      borderSubtle: '#c4cbd8',
      textPrimary: '#2e3440',
      textSecondary: '#3b4252',
      textMuted: '#4c566a',
      accent: '#5e81ac',
      accentHover: '#4c6e97',
      accentMuted: 'rgba(94, 129, 172, 0.15)',
      accentText: '#3b5a80',
      series: {
        neutral: '#4c566a',
        green: '#8fbcbb',
        orange: '#d08770',
        blue: '#5e81ac',
        purple: '#b48ead',
        amber: '#ebcb8b',
        red: '#bf616a',
        teal: '#88c0d0',
      },
      boxGradient: {
        start: '#8fbcbb',
        end: '#2e3440',
      },
    },
  },
  'rose-pine-dawn': {
    name: 'Rose Pine Dawn',
    mode: 'light',
    description:
      'Warm botanical parchment with soft tea rose, eucalyptus pine, and golden sunlight',
    colors: {
      bgApp: '#faf4ed',
      bgCard: '#fffaf3',
      bgSubtle: '#f2e9e1',
      bgHover: '#e8ddcf',
      border: '#dfdad0',
      borderSubtle: '#cecaa1',
      textPrimary: '#575279',
      textSecondary: '#797593',
      textMuted: '#9893a5',
      accent: '#b4637a',
      accentHover: '#9a4b62',
      accentMuted: 'rgba(180, 99, 122, 0.15)',
      accentText: '#82374e',
      series: {
        neutral: '#797593',
        green: '#286983',
        orange: '#ea9d34',
        blue: '#56949f',
        purple: '#907aa9',
        amber: '#d7827e',
        red: '#b4637a',
        teal: '#2aa198',
      },
      boxGradient: {
        start: '#d7827e',
        end: '#286983',
      },
    },
  },
  'mint-light': {
    name: 'Garden Mint',
    mode: 'light',
    description:
      'Fresh botanical matcha and spearmint companion to GAN Mint with deep forest typography',
    colors: {
      bgApp: '#f0fdf4',
      bgCard: '#ffffff',
      bgSubtle: '#dcfce7',
      bgHover: '#bbf7d0',
      border: '#bbf7d0',
      borderSubtle: '#86efac',
      textPrimary: '#064e3b',
      textSecondary: '#065f46',
      textMuted: '#047857',
      accent: '#059669',
      accentHover: '#047857',
      accentMuted: 'rgba(5, 150, 105, 0.15)',
      accentText: '#064e3b',
      series: {
        neutral: '#047857',
        green: '#059669',
        orange: '#ea580c',
        blue: '#0284c7',
        purple: '#7c3aed',
        amber: '#b45309',
        red: '#dc2626',
        teal: '#0891b2',
      },
      boxGradient: {
        start: '#6ee7b7',
        end: '#064e3b',
      },
    },
  },
  latte: {
    name: 'Catppuccin Latte',
    mode: 'light',
    description: 'Soothing pastel light palette with lavender, peach, and sapphire',
    colors: {
      bgApp: '#eff1f5',
      bgCard: '#ffffff',
      bgSubtle: '#e6e9ef',
      bgHover: '#dce0e8',
      border: '#ccd0da',
      borderSubtle: '#bcc0cc',
      textPrimary: '#4c4f69',
      textSecondary: '#5c5f77',
      textMuted: '#6c6f85',
      accent: '#8839ef',
      accentHover: '#7287fd',
      accentMuted: 'rgba(136, 57, 239, 0.15)',
      accentText: '#8839ef',
      series: {
        neutral: '#7287fd',
        green: '#1e66f5',
        orange: '#fe640b',
        blue: '#209fb5',
        purple: '#8839ef',
        amber: '#df8e1d',
        red: '#d20f39',
        teal: '#179299',
      },
      boxGradient: {
        start: '#8839ef',
        end: '#1e66f5',
      },
    },
  },
  'tokyo-night-day': {
    name: 'Tokyo Night Day',
    mode: 'light',
    description: 'High-clarity Japanese cityscape light theme with cobalt blue and cyan',
    colors: {
      bgApp: '#e1e2e7',
      bgCard: '#ffffff',
      bgSubtle: '#d5d6db',
      bgHover: '#c4c8da',
      border: '#c4c8da',
      borderSubtle: '#a8aecb',
      textPrimary: '#3760bf',
      textSecondary: '#485e94',
      textMuted: '#6172b0',
      accent: '#2e7de9',
      accentHover: '#1859c2',
      accentMuted: 'rgba(46, 125, 233, 0.15)',
      accentText: '#1859c2',
      series: {
        neutral: '#a8aecb',
        green: '#2e7de9',
        orange: '#b15c00',
        blue: '#007197',
        purple: '#9854f1',
        amber: '#8c6c00',
        red: '#f52a65',
        teal: '#0db9d7',
      },
      boxGradient: {
        start: '#2e7de9',
        end: '#007197',
      },
    },
  },
} satisfies Record<string, ThemeSpec>;

/** The set of available theme ids, derived from the registry — never hand-listed. */
export type ThemeId = keyof typeof THEME_SPECS;

/** A fully resolved theme: its registry key plus the theme data. */
export interface ThemeDefinition extends ThemeSpec {
  id: ThemeId;
}

export const THEMES = Object.fromEntries(
  (Object.keys(THEME_SPECS) as ThemeId[]).map((id): [ThemeId, ThemeDefinition] => [
    id,
    { id, ...THEME_SPECS[id] },
  ]),
) as Record<ThemeId, ThemeDefinition>;

export const THEMES_LIST: ThemeDefinition[] = Object.values(THEMES);

/** The default theme, used when no preference is stored and as the unknown-id fallback. */
export const darkTheme: ThemeDefinition = THEMES.dark;

export function getTheme(id: string): ThemeDefinition {
  return THEMES[id as ThemeId] ?? darkTheme;
}
